-- parser limits: nesting (the C stack limit) and locals per function
local function try(src, name)
  local f, msg = load(src, name)
  print(f ~= nil, msg)
end
try(string.rep("(", 300), "=nest")
try("return " .. string.rep("a..", 300), "=concat")
try("local a; a" .. string.rep(",a", 300) .. "= 1", "=targets")
try(string.rep("do ", 300), "=blocks")
try("return " .. string.rep("not ", 300), "=unary")
try("return " .. string.rep("a+", 300) .. "a", "=leftassoc")
try("local a" .. string.rep(",a", 199), "=locals200")
try("local a" .. string.rep(",a", 200), "=locals201")
try("function f(x) local a" .. string.rep(",a", 199) .. " end", "=params")
try("local a for i = 1, 2 do local b" .. string.rep(",b", 195) .. " end", "=forlocals")
try("local a for i = 1, 2 do local b" .. string.rep(",b", 196) .. " end", "=forlocals2")
try("for k, v" .. string.rep(",w", 194) .. " in pairs({}) do end", "=forin")
try("do local a end local b" .. string.rep(",b", 199), "=scoped")
try("local x <const> = 1; x = 2", "=const")
try("local x <const> = 1; local function f() x = 2 end", "=constup")
print(pcall(load, string.rep("{", 400), "=braces")) -- an explicit chunk name: the installed reference truncates chunk ids differently (LUA_IDSIZE 512)
print(select(2, pcall(load, "return " .. string.rep("a(", 400))))
