-- table.insert / remove / unpack and ipairs on plain tables, proxies and holes
local function show(t, n) local o = {} for i = 1, n or #t do o[i] = tostring(t[i]) end return table.concat(o, ",") end
local t = {1, 2, 3} table.insert(t, 4) table.insert(t, 1, 0) table.insert(t, 3, 2.5) print(show(t))
print(pcall(table.insert, t, 0, 9), pcall(table.insert, t, #t + 2, 9), pcall(table.insert, t), pcall(table.insert, t, 1, 2, 3))
table.insert(t, #t + 1, "end") print(show(t))
print(table.remove(t), table.remove(t, 1), table.remove(t, 3), show(t))
print(pcall(table.remove, t, 0), pcall(table.remove, t, #t + 2), table.remove(t, #t + 1), table.remove({}), table.remove({}, 0), show(t))
local e = {} print(table.remove(e), #e, table.remove(e, 1))
print(table.unpack({1, 2, 3}), table.unpack({1, 2, 3}, 2), table.unpack({1, 2, 3}, 2, 3), table.unpack({1, 2, 3}, 3, 2), table.unpack({}, 1, 2))
print(select("#", table.unpack({1, nil, 3})), table.unpack({1, nil, 3}, 1, 3))
print(pcall(table.unpack, {}, 1, 1e8), pcall(table.unpack, {}, math.mininteger, math.maxinteger))
local h = {} h[1] = "a" h[2] = "b" h[4] = "d" print(table.unpack(h, 1, 4)) table.insert(h, 3, "c") print(show(h, 4))
local p = setmetatable({}, {__index = function(_, i) if i <= 3 then return i * 10 end end, __newindex = function(s, k, v) rawset(s, k, v) print("newindex", k, v) end, __len = function() return 3 end})
print(table.unpack(p)) table.insert(p, 40) table.insert(p, 1, 5) print(rawget(p, 4), rawget(p, 1), table.remove(p))
for i, v in ipairs({10, 20, nil, 40}) do io.write(i, "=", v, " ") end print()
for i, v in ipairs(p) do io.write(i, "=", tostring(v), " ") end print()
local big = {} for i = 1, 100 do big[i] = i end for i = 1, 50 do table.remove(big, 1) end table.insert(big, 1, -1) print(#big, big[1], big[2], big[51], big[52])
local q = {} for i = 1, 10 do table.insert(q, i) end for i = 1, 5 do table.insert(q, 1, -i) end print(show(q))
print(#{table.unpack(q)}, select("#", table.unpack(q, 3)))
